# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep_logz <- function(m, K, lb, ub) {
    .Call(`_graphml_ep_logz`, m, K, lb, ub)
}

getJT <- function(EdgeMat) {
    .Call(`_graphml_getJT`, EdgeMat)
}

log_exp_mc <- function(G, nu, b, H, check_H, mc, p) {
    .Call(`_graphml_log_exp_mc`, G, nu, b, H, check_H, mc, p)
}

gnorm_c <- function(Adj, b, D, iter) {
    .Call(`_graphml_gnorm_c`, Adj, b, D, iter)
}

log_multi_gamma <- function(p, n) {
    .Call(`_graphml_log_multi_gamma`, p, n)
}

log_wishart_norm <- function(p, b, D) {
    .Call(`_graphml_log_wishart_norm`, p, b, D)
}

gnormJT <- function(Adj, EdgeMat, b, D, iter = 500L) {
    .Call(`_graphml_gnormJT`, Adj, EdgeMat, b, D, iter)
}

init_graph <- function(G, b, V) {
    .Call(`_graphml_init_graph`, G, b, V)
}

generalApprox <- function(G, b, V, J) {
    .Call(`_graphml_generalApprox`, G, b, V, J)
}

approx_v1 <- function(u_df, uStar, data, params) {
    .Call(`_graphml_approx_v1`, u_df, uStar, data, params)
}

approx_integral <- function(K, psi_df, bounds, params) {
    .Call(`_graphml_approx_integral`, K, psi_df, bounds, params)
}

evalPsi <- function(samps, params) {
    .Call(`_graphml_evalPsi`, samps, params)
}

calcMode <- function(u_df, params) {
    .Call(`_graphml_calcMode`, u_df, params)
}

support <- function(samps, D) {
    .Call(`_graphml_support`, samps, D)
}

fitTree <- function(x, formula) {
    .Call(`_graphml_fitTree`, x, formula)
}

findAllCandidatePoints <- function(data, locs, uStar, D) {
    .Call(`_graphml_findAllCandidatePoints`, data, locs, uStar, D)
}

createPartitionMap <- function(bounds, leafId) {
    .Call(`_graphml_createPartitionMap`, bounds, leafId)
}

getPartition <- function(tree, supp) {
    .Call(`_graphml_getPartition`, tree, supp)
}

rcpparma_hello_world <- function() {
    .Call(`_graphml_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_graphml_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_graphml_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_graphml_rcpparma_bothproducts`, x)
}

rgw <- function(J, obj) {
    .Call(`_graphml_rgw`, J, obj)
}

rwish_c <- function(Ts, b, p) {
    .Call(`_graphml_rwish_c`, Ts, b, p)
}

rgwish_c <- function(G, Ts, b, p, threshold_c) {
    .Call(`_graphml_rgwish_c`, G, Ts, b, p, threshold_c)
}

createDfName <- function(D) {
    .Call(`_graphml_createDfName`, D)
}

mat2df <- function(x, nameVec) {
    .Call(`_graphml_mat2df`, x, nameVec)
}

lse <- function(arr, count) {
    .Call(`_graphml_lse`, arr, count)
}

